### ISSUE TITLE
Regarding sdpid of controller and clients

### ISSUE THREAD

**Issue by Xavier-Josephh** [WaverleyLabs/SDPcontroller#1]
Hi, 

I have installed this SDPcontroller in my machine, I  see that while creating certificates it is asking for sdpid for both controller & client. I was able to connect to first client. 

To connect to a second client I only generated client certificates with different sdpid and pasted in the client machine but I'm not able to connect to controller from second client. I'm getting an error as SSL handshake failed. 

Is there any solution for this?Thank you.

**Comment by hydrolucid** [comment]
Hi, 

The controller is certainly capable of connecting to multiple clients. It sounds like something went wrong while creating your second set of credentials. Your question reminded me that I needed to update the README.md file with new instructions for generating credentials, so I did that just now. Please see the latest version, specifically steps 8 through 12, for a more automated way to generate the client certificate and keys which reduces risk of mistakes. If that fails, please let me know and we'll go from there. 

Thanks, 
Daniel Bailey 
Waverley Labs, LLC 
PO Box 213 
Waterford, VA 20197 

dbailey@waverleylabs.com 
waverleylabs.com

**Comment by Xavier-Josephh** [comment]
Hi,

I will follow the steps 8 through 12 and will get back if I find any issues again.

Thank you.

**Comment by gigi-goren** [comment]
Hi,

When running the SDPController.js I get the following error:
/opt/SDPcontroller-master/sdpController.js:381
                    };

looks like json problem, in the file I see the following:

 newEntry = {
                        sdpId: memberDetails.sdpid,
                        connectionId: connectionId,
                        connectionTime: new Date(),
                        socket
                    };

Any solution for that ?

Sagiv

**Comment by hydrolucid** [comment]
Hi Sagiv,

Your question is unrelated to this issue thread. Also, you did not provide an adequate error report for me to understand the issue at hand. Please open a new issue with a more clear summary of the problem. I will be deleting your comment from this issue thread.

Thanks,
Dan

**Comment by hydrolucid** [comment]
Hi,
I'm closing this issue since it appears no further issue was experienced.

**Comment by gigi-goren** [comment]
Hi,

while in step 12, I get the following error:
sudo node ./genCredentials.js 3333

Preparing to generate credentials for SDP ID 3333
Error: Invalid openssl exit code: 1
% openssl req -new -sha256 -subj /C=israel/ST=israel/L=israel/O=israel/CN=3333 -key /tmp/9bdfd84e0def2bf0609117ec2de8ed139fa24c77
problems making Certificate Request
140697305052840:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=2

can you send an example of the data I need in order to populate the tables.
the current data I have is the following :
table - sdpid
*************************** 1. row ***************************
           sdpid: 1111
           valid: 1
            type: client
         country: israel
           state: israel
        locality: israel
             org: israel
        org_unit: NULL
        alt_name: NULL
           email: NULL
     encrypt_key: NULL
        hmac_key: NULL
          serial: 
last_cred_update: 0000-00-00 00:00:00
 cred_update_due: 0000-00-00 00:00:00
         user_id: NULL
  environment_id: NULL
*************************** 2. row ***************************
           sdpid: 2222
           valid: 1
            type: gateway
         country: israel
           state: israel
        locality: israel
             org: israel
        org_unit: NULL
        alt_name: NULL
           email: NULL
     encrypt_key: NULL
        hmac_key: NULL
          serial: 
last_cred_update: 0000-00-00 00:00:00
 cred_update_due: 0000-00-00 00:00:00
         user_id: NULL
  environment_id: NULL
*************************** 3. row ***************************
           sdpid: 3333
           valid: 1
            type: controller
         country: israel
           state: israel
        locality: israel
             org: israel
        org_unit: NULL
        alt_name: NULL
           email: NULL
     encrypt_key: NULL
        hmac_key: NULL
          serial: 
last_cred_update: 0000-00-00 00:00:00
 cred_update_due: 0000-00-00 00:00:00
         user_id: NULL
  environment_id: NULL


table - service
*************************** 1. row ***************************
         id: 3333
       name: controller
description: controller

table - service_gateway
*************************** 1. row ***************************
           id: 6
   service_id: 3333
gateway_sdpid: 2222
     protocol: 
         port: 0
       nat_ip: 
     nat_port: 0

please advice,

Thanks

**Comment by hydrolucid** [comment]
Hi, 

Thank you for the detailed error report. I think I see the problem. For some reason, OpenSSL requires that the country must be entered as a two-letter code, such as US rather than USA. It's failing on your country entry, 'Israel'. I believe if you change that to a two letter entry in your database, it should work. I will have to make a note about that somewhere for future users. Let me know if this solves the problem and thank you for your patience. 

Sincerely, 
Dan

**Comment by cloudlakecho** [comment]
@gigi-goren Thanks for sharing your error with detailed tables. I have two questions:

Does "country" value change as suggested fixed the error?

Where do you find example of the Table Field? I couldn't find anywhere in  [Read Me](https://github.com/WaverleyLabs/fwknop), [turtorial](http://www.cipherdyne.org/fwknop/docs/) nor [fwknop](https://github.com/WaverleyLabs/fwknop).
